const $=s=>document.querySelector(s);
const STORAGE_KEY="euro-goal-rush-live-draw-v1",CREST_CACHE_KEY="euro-goal-rush-draw-crests-v1",PLACEHOLDER="crest-placeholder.svg";
const els={setup:$("#setup-screen"),live:$("#live-screen"),entrants:$("#entrant-list"),ucl:$("#ucl-list"),uel:$("#uel-list"),entrantCount:$("#entrant-count"),uclCount:$("#ucl-count"),uelCount:$("#uel-count"),note:$("#setup-note"),start:$("#start-btn"),demo:$("#demo-btn"),entrantsLeft:$("#entrants-left"),uclLeft:$("#ucl-left"),uelLeft:$("#uel-left"),drawNumber:$("#draw-number"),entrantReveal:$("#entrant-reveal"),uclReveal:$("#ucl-reveal"),uelReveal:$("#uel-reveal"),uclCrest:$("#ucl-reveal-crest"),uelCrest:$("#uel-reveal-crest"),entrantPanel:$("#entrant-panel"),uclPanel:$("#ucl-panel"),uelPanel:$("#uel-panel"),drawEntrant:$("#draw-entrant-btn"),drawUcl:$("#draw-ucl-btn"),drawUel:$("#draw-uel-btn"),confirm:$("#confirm-btn"),completed:$("#completed-count"),total:$("#total-count"),body:$("#results-body"),undo:$("#undo-btn"),copy:$("#copy-btn"),csv:$("#csv-btn"),json:$("#json-btn"),reset:$("#reset-btn"),fullscreen:$("#fullscreen-btn"),uclAudioBtn:$("#draw-ucl-audio"),uelAudioBtn:$("#draw-uel-audio"),uclAudio:$("#draw-ucl-track"),uelAudio:$("#draw-uel-track")};
let state={entrantsPool:[],uclPool:[],uelPool:[],results:[],current:{entrant:null,ucl:null,uel:null},total:0},crestCache=loadJson(CREST_CACHE_KEY,{}),busy=false;
function loadJson(k,f){try{return JSON.parse(localStorage.getItem(k)||"")||f}catch{return f}}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function cleanLines(v){return v.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}function unique(a){return new Set(a.map(v=>v.toLocaleLowerCase())).size===a.length}
function secureIndex(n){const max=0x100000000,limit=max-(max%n),a=new Uint32Array(1);do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%n}function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function validateSetup(){const a=cleanLines(els.entrants.value),b=cleanLines(els.ucl.value),c=cleanLines(els.uel.value);els.entrantCount.textContent=a.length;els.uclCount.textContent=b.length;els.uelCount.textContent=c.length;let msg="",ok=false;if(!a.length&&!b.length&&!c.length)msg="Add the three lists to begin.";else if(!unique(a)||!unique(b)||!unique(c))msg="Each list must contain unique entries only.";else if(a.length!==b.length||a.length!==c.length)msg="All three lists must contain the same number of items.";else if(a.length<2)msg="Add at least two entries to each list.";else{ok=true;msg=`Ready for a ${a.length}-entrant live draw.`}els.note.textContent=msg;els.note.className="setup-note "+(ok?"good":(a.length||b.length||c.length?"bad":""));els.start.disabled=!ok;return ok?{entrants:a,ucl:b,uel:c}:null}
function startDraw(){const v=validateSetup();if(!v)return;state={entrantsPool:[...v.entrants],uclPool:[...v.ucl],uelPool:[...v.uel],results:[],current:{entrant:null,ucl:null,uel:null},total:v.entrants.length};save();showLive();render()}
function showLive(){els.setup.hidden=true;els.live.hidden=false}function restoreSession(){const x=loadJson(STORAGE_KEY,null);if(!x?.total)return false;state=x;showLive();render();return true}
function render(){els.entrantsLeft.textContent=state.entrantsPool.length;els.uclLeft.textContent=state.uclPool.length;els.uelLeft.textContent=state.uelPool.length;els.total.textContent=state.total;els.completed.textContent=state.results.length;els.drawNumber.textContent=String(Math.min(state.results.length+1,state.total)).padStart(2,"0");els.entrantReveal.textContent=state.current.entrant||"Ready";els.uclReveal.textContent=state.current.ucl||"—";els.uelReveal.textContent=state.current.uel||"—";setCrest(els.uclCrest,state.current.ucl);setCrest(els.uelCrest,state.current.uel);const done=state.results.length===state.total;document.body.classList.toggle("draw-complete",done);els.drawEntrant.disabled=busy||done||!!state.current.entrant;els.drawUcl.disabled=busy||done||!state.current.entrant||!!state.current.ucl;els.drawUel.disabled=busy||done||!state.current.ucl||!!state.current.uel;els.confirm.disabled=busy||done||!(state.current.entrant&&state.current.ucl&&state.current.uel);els.undo.disabled=busy||!state.results.length||!!state.current.entrant;const has=state.results.length>0;els.copy.disabled=!has;els.csv.disabled=!has;els.json.disabled=!has;renderResults();save()}
function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/\p{Diacritic}/gu,"").replace(/[^a-z0-9]/g,"")}
function setCrest(img,team){img.src=team?(crestCache[team.toLowerCase()]||PLACEHOLDER):PLACEHOLDER;if(team&&!crestCache[team.toLowerCase()])hydrateCrest(team,img)}
async function hydrateCrest(team,img){try{const r=await fetch(`https://www.thesportsdb.com/api/v1/json/123/searchteams.php?t=${encodeURIComponent(team)}`),j=await r.json(),soccer=(j.teams||[]).filter(t=>t.strSport==="Soccer"),match=soccer.find(t=>norm(t.strTeam)===norm(team))||soccer[0];if(match?.strBadge){crestCache[team.toLowerCase()]=match.strBadge;localStorage.setItem(CREST_CACHE_KEY,JSON.stringify(crestCache));img.src=match.strBadge;renderResults()}}catch{}}
async function animateReveal(pool,panel,text,finalValue){busy=true;panel.classList.add("is-spinning");const start=performance.now();while(performance.now()-start<1250){text.textContent=pool[secureIndex(pool.length)]||finalValue;await sleep(70)}text.textContent=finalValue;panel.classList.remove("is-spinning");panel.classList.remove("is-revealed");void panel.offsetWidth;panel.classList.add("is-revealed");busy=false}
async function drawFrom(kind){if(busy)return;const pool=state[kind+"Pool"];if(!pool.length)return;const idx=secureIndex(pool.length),winner=pool[idx],panel=kind==="entrants"?els.entrantPanel:(kind==="ucl"?els.uclPanel:els.uelPanel),text=kind==="entrants"?els.entrantReveal:(kind==="ucl"?els.uclReveal:els.uelReveal);await animateReveal(pool,panel,text,winner);pool.splice(idx,1);if(kind==="entrants")state.current.entrant=winner;else state.current[kind]=winner;render()}
function confirmCurrent(){if(!(state.current.entrant&&state.current.ucl&&state.current.uel))return;state.results.push({...state.current});state.current={entrant:null,ucl:null,uel:null};render()}
function undoLast(){const x=state.results.pop();if(!x)return;state.entrantsPool.push(x.entrant);state.uclPool.push(x.ucl);state.uelPool.push(x.uel);render()}
function renderResults(){if(!state.results.length){els.body.innerHTML='<tr class="empty-row"><td colspan="4">No completed draws yet.</td></tr>';return}els.body.innerHTML=state.results.map((r,i)=>`<tr><td>${i+1}</td><td><strong>${esc(r.entrant)}</strong></td><td><div class="result-team"><img src="${crestCache[r.ucl.toLowerCase()]||PLACEHOLDER}" alt=""><span>${esc(r.ucl)}</span></div></td><td><div class="result-team"><img src="${crestCache[r.uel.toLowerCase()]||PLACEHOLDER}" alt=""><span>${esc(r.uel)}</span></div></td></tr>`).join("")}
function download(name,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function csvText(){return ["Position,Entrant,UCL Team,UEL Team",...state.results.map((r,i)=>`${i+1},"${r.entrant.replaceAll('"','""')}","${r.ucl.replaceAll('"','""')}","${r.uel.replaceAll('"','""')}"`)].join("\n")}
async function competitionJson(){let base={brandName:"EURO GOAL RUSH 26/27",season:"2026/27",entries:[]};try{const r=await fetch("competition.json?v=40",{cache:"no-store"});if(r.ok)base=await r.json()}catch{}base.entries=state.results.map((r,i)=>({id:i+1,entrant:r.entrant,previousRank:null,ucl:{club:r.ucl,crest:crestCache[r.ucl.toLowerCase()]||"",apiTeamId:null,apiCode:"",played:0,goalsFor:0,goalsAgainst:0,fixtures:Array.from({length:8},()=>({code:"TBD",venue:"",status:""}))},uel:{club:r.uel,crest:crestCache[r.uel.toLowerCase()]||"",apiTeamId:null,apiCode:"",played:0,goalsFor:0,goalsAgainst:0,fixtures:Array.from({length:8},()=>({code:"TBD",venue:"",status:""}))}}));return JSON.stringify(base,null,2)+"\n"}
function wireAudio(btn,audio,otherBtn,otherAudio){btn.addEventListener("click",async()=>{if(!audio.paused){audio.pause();audio.currentTime=0;btn.classList.remove("is-playing");return}otherAudio.pause();otherAudio.currentTime=0;otherBtn.classList.remove("is-playing");try{await audio.play();btn.classList.add("is-playing")}catch{alert("Upload the matching anthem MP3 to the repository root.")}});audio.addEventListener("ended",()=>btn.classList.remove("is-playing"))}
[els.entrants,els.ucl,els.uel].forEach(x=>x.addEventListener("input",validateSetup));els.start.addEventListener("click",startDraw);els.drawEntrant.addEventListener("click",()=>drawFrom("entrants"));els.drawUcl.addEventListener("click",()=>drawFrom("ucl"));els.drawUel.addEventListener("click",()=>drawFrom("uel"));els.confirm.addEventListener("click",confirmCurrent);els.undo.addEventListener("click",()=>{if(confirm("Undo the last confirmed draw?"))undoLast()});els.copy.addEventListener("click",async()=>{await navigator.clipboard.writeText(state.results.map((r,i)=>`${i+1}. ${r.entrant} — ${r.ucl} / ${r.uel}`).join("\n"));els.copy.textContent="Copied";setTimeout(()=>els.copy.textContent="Copy results",1200)});els.csv.addEventListener("click",()=>download("euro-goal-rush-draw.csv",csvText(),"text/csv"));els.json.addEventListener("click",async()=>download("competition.json",await competitionJson(),"application/json"));els.reset.addEventListener("click",()=>{if(confirm("Reset the entire draw? This cannot be undone.")){localStorage.removeItem(STORAGE_KEY);location.reload()}});els.fullscreen.addEventListener("click",()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());
wireAudio(els.uclAudioBtn,els.uclAudio,els.uelAudioBtn,els.uelAudio);wireAudio(els.uelAudioBtn,els.uelAudio,els.uclAudioBtn,els.uclAudio);
els.demo.addEventListener("click",async()=>{try{const r=await fetch("competition.json?v=40",{cache:"no-store"}),d=await r.json();els.entrants.value=d.entries.map(e=>e.entrant).join("\n");els.ucl.value=d.entries.map(e=>e.ucl.club).join("\n");els.uel.value=d.entries.map(e=>e.uel.club).join("\n");validateSetup()}catch{alert("Could not load demo data.")}});
if(!restoreSession())validateSetup();
